/**
 * Spindle-on-hours tracking: accumulates seconds of spindle-on time entirely on the controller, so
 * the total is correct whenever DWC happens to reconnect, not just for the time it was watching.
 *
 * RRF's `global.xxx` variables are RAM-only (confirmed against RRF source - no flash/SD backing), so a
 * counter needs its own persistence: `maintenance-daemon.g` accumulates into `global.flMaintSpindleSec`
 * every time it runs, and periodically calls `maintenance-flush.g` to write that value out to
 * `0:/sys/flexible-layouts.maintenance-state.g` using the Duet3D wiki's documented "persistentGlobal.g"
 * pattern (`echo >`/`echo >>` writing `set`/`global` statements) - restored by `config.g` calling
 * `M98 P"0:/sys/flexible-layouts.maintenance-state.g"` early at boot (see configPatch.ts).
 *
 * These two macros are deployed to their own folder, the same way util/xyzProbe.ts deploys its probe
 * macros - NEVER as FL's own daemon.g outright, since daemon.g is a single file with no
 * multi-contribution mechanism and clobbering a user's own daemon.g customization would repeat
 * exactly the mistake xyzProbe.ts's own macros already had fixed for them. The setup wizard instead
 * detects/offers to add one M98 line to the user's own daemon.g (see configPatch.ts).
 *
 * Which spindle to track (`global.flMaintSpindleIndex`) lives in the SAME persisted-state file as the
 * accumulated seconds, restored together - so changing the tracked spindle is just a setup-wizard
 * re-run, never a macro redeploy. The daemon macro itself is static content, indexing `spindles[]`
 * dynamically by that persisted value.
 */
import type { MachineIO } from "dwc-config-backup-core";

export const MAINTENANCE_MACRO_FOLDER = "0:/macros/FlexibleLayouts";
export const MAINTENANCE_DAEMON_FILE = "maintenance-daemon.g";
export const MAINTENANCE_FLUSH_FILE = "maintenance-flush.g";
export const MAINTENANCE_STATE_PATH = "0:/sys/flexible-layouts.maintenance-state.g";

/** Bumped whenever a change to these macro templates matters enough that an already-deployed copy
 *  should be flagged as outdated - see {@link maintenanceMacrosOutdated}. */
export const MAINTENANCE_MACRO_SET_VERSION = 1;

const VERSION_MARKER_RE = /;\s*FL-MAINTENANCE-MACRO-VERSION:\s*(\d+)/;

export function extractMaintenanceMacroVersion(text: string): number {
	const m = text.match(VERSION_MARKER_RE);
	return m ? parseInt(m[1], 10) : 0;
}

function macroHeader(title: string): string {
	return `; ${title}
; FL-MAINTENANCE-MACRO-VERSION: ${MAINTENANCE_MACRO_SET_VERSION}
; Part of Flexible Layouts' machine maintenance tracking.
;
; This file is yours to customize. Just leave the global.flMaint* variables alone - they're what
; Flexible Layouts reads back to compute spindle-on hours.

`;
}

/** Polls the tracked spindle's state and accumulates on-time. Bails out immediately (M99, "return
 *  from macro") if the persisted state hasn't been restored yet - config.g hasn't run
 *  maintenance-state.g, or setup hasn't completed - rather than accumulating against undeclared
 *  globals. Amount-based (not interval-based) flush trigger bounds SD writes to roughly once per 10
 *  minutes of continuous spindle-on time, regardless of how often this macro itself gets polled. */
export const MAINTENANCE_DAEMON_MACRO = macroHeader("maintenance-daemon.g - spindle-hours accumulator") + `if !exists(global.flMaintSpindleIndex)
	M99

if !exists(global.flMaintLastPollTime)
	global flMaintLastPollTime = state.upTime
	global flMaintUnflushedSec = 0

var dt = state.upTime - global.flMaintLastPollTime
; state.upTime resets to 0 on reboot - without this clamp, a reboot between two polls would show as
; a large negative delta and corrupt the accumulator instead of just losing that one interval.
if var.dt < 0
	set var.dt = 0
set global.flMaintLastPollTime = state.upTime

var spindleState = spindles[global.flMaintSpindleIndex].state
if var.spindleState == "forward" || var.spindleState == "reverse"
	set global.flMaintSpindleSec = global.flMaintSpindleSec + var.dt
	set global.flMaintUnflushedSec = global.flMaintUnflushedSec + var.dt

if global.flMaintUnflushedSec >= 600
	M98 P"${MAINTENANCE_MACRO_FOLDER}/${MAINTENANCE_FLUSH_FILE}"
	set global.flMaintUnflushedSec = 0
`;

/** Writes the accumulated counters to a small persistent-globals file (the Duet3D wiki's documented
 *  pattern for surviving a reboot, since global.* itself doesn't) - restored by config.g at boot. */
export const MAINTENANCE_FLUSH_MACRO = macroHeader("maintenance-flush.g - persists the spindle-hours counter") + `echo >"${MAINTENANCE_STATE_PATH}" "; Auto-generated by Flexible Layouts - do not edit by hand"
echo >>"${MAINTENANCE_STATE_PATH}" "if !exists(global.flMaintSpindleIndex)"
echo >>"${MAINTENANCE_STATE_PATH}" "  global flMaintSpindleIndex = " ^ global.flMaintSpindleIndex
echo >>"${MAINTENANCE_STATE_PATH}" "else"
echo >>"${MAINTENANCE_STATE_PATH}" "  set global.flMaintSpindleIndex = " ^ global.flMaintSpindleIndex
echo >>"${MAINTENANCE_STATE_PATH}" "endif"
echo >>"${MAINTENANCE_STATE_PATH}" "if !exists(global.flMaintSpindleSec)"
echo >>"${MAINTENANCE_STATE_PATH}" "  global flMaintSpindleSec = " ^ global.flMaintSpindleSec
echo >>"${MAINTENANCE_STATE_PATH}" "else"
echo >>"${MAINTENANCE_STATE_PATH}" "  set global.flMaintSpindleSec = " ^ global.flMaintSpindleSec
echo >>"${MAINTENANCE_STATE_PATH}" "endif"
`;

export const MAINTENANCE_MACROS: Record<string, string> = {
	[MAINTENANCE_DAEMON_FILE]: MAINTENANCE_DAEMON_MACRO,
	[MAINTENANCE_FLUSH_FILE]: MAINTENANCE_FLUSH_MACRO,
};

/** Upload both macro files (unconditionally - used for both first-time deploy and "Redeploy macros"). */
export async function deployMaintenanceMacros(io: Pick<MachineIO, "upload">): Promise<boolean> {
	try {
		for (const [name, content] of Object.entries(MAINTENANCE_MACROS)) {
			await io.upload(`${MAINTENANCE_MACRO_FOLDER}/${name}`, new Blob([content], { type: "text/plain" }));
		}
		return true;
	} catch {
		return false;
	}
}

/** Whether the daemon macro needs deploying at all (checked via a download attempt). */
export async function maintenanceMacrosMissing(io: Pick<MachineIO, "downloadText">): Promise<boolean> {
	try {
		await io.downloadText(`${MAINTENANCE_MACRO_FOLDER}/${MAINTENANCE_DAEMON_FILE}`);
		return false;
	} catch {
		return true;
	}
}

/** Present-but-stale detection, same "never silently overwrite, only flag" contract as
 *  xyzProbe.ts's xyzProbeMacrosOutdated - only meaningful once the file is known to exist. A
 *  download failure is ambiguous (offline vs. genuinely fine), so it resolves to false. */
export async function maintenanceMacrosOutdated(io: Pick<MachineIO, "downloadText">): Promise<boolean> {
	try {
		const text = await io.downloadText(`${MAINTENANCE_MACRO_FOLDER}/${MAINTENANCE_DAEMON_FILE}`);
		return extractMaintenanceMacroVersion(text) < MAINTENANCE_MACRO_SET_VERSION;
	} catch {
		return false;
	}
}

/** Writes the persisted-state file directly (setup, or re-running setup to change the tracked
 *  spindle - the flush macro can't do this itself, since it only ever writes the CURRENT live values,
 *  and on a true first run nothing has accumulated yet to call it) and reloads it immediately via M98
 *  so tracking starts/updates live, without waiting for a reboot. Uses the same if-exists/else-set
 *  pattern as the flush macro (not a bare `global x = ...`) because this can run again later in the
 *  same boot session, after the daemon macro has already declared these globals once - re-declaring
 *  an existing global with the bare `global` keyword is an error in RRF, only `set global.x = ...` is
 *  safe on an already-existing one. `spindleSeconds` lets re-running setup preserve an
 *  already-accumulated total rather than resetting it. */
export async function seedMaintenanceState(
	io: Pick<MachineIO, "upload" | "sendCode">, spindleIndex: number, spindleSeconds = 0,
): Promise<boolean> {
	const content = `; Auto-generated by Flexible Layouts - do not edit by hand
if !exists(global.flMaintSpindleIndex)
	global flMaintSpindleIndex = ${spindleIndex}
else
	set global.flMaintSpindleIndex = ${spindleIndex}
if !exists(global.flMaintSpindleSec)
	global flMaintSpindleSec = ${spindleSeconds}
else
	set global.flMaintSpindleSec = ${spindleSeconds}
`;
	try {
		await io.upload(MAINTENANCE_STATE_PATH, new Blob([content], { type: "text/plain" }));
		await io.sendCode(`M98 P"${MAINTENANCE_STATE_PATH}"`);
		return true;
	} catch {
		return false;
	}
}
