/**
 * A tiny macro that does the full stop/start cycle needed to (re-)enable TLS on the network interface -
 * `M552 S0` to disable it, a short settle delay, then `M552 T1 S1` to bring it back up with TLS active -
 * deployed to the plugin's own macro folder and run via a single `M98`, rather than sent as two (or
 * more) separate live commands.
 *
 * Confirmed on real hardware: sending `M552 S0` and then `M552 T1 S1` as two separate live commands
 * doesn't reliably re-enable TLS - once S0 drops the very interface DWC itself is connected through, a
 * follow-up command sent as its own request over that same connection either never arrives or is
 * silently ignored, even after waiting for the interface to visibly reconnect. Running the whole
 * sequence as one macro via `M98` instead hands it to RRF's own gcode-file execution, which keeps
 * running every line regardless of what happens to the connection that kicked it off.
 */
import type { MachineIO } from "dwc-config-backup-core";

// Same "this plugin's own generated macros" folder maintenance/macros.ts deploys into
// (MAINTENANCE_MACRO_FOLDER) - kept as its own literal here rather than a shared import, since the two
// features' macro sets are otherwise unrelated and don't need to change together.
export const TLS_MACRO_FOLDER = "0:/macros/FlexibleLayouts";
export const TLS_ENABLE_INTERFACE_FILE = "enable-tls-interface.g";
export const TLS_ENABLE_INTERFACE_PATH = `${TLS_MACRO_FOLDER}/${TLS_ENABLE_INTERFACE_FILE}`;

export const TLS_ENABLE_INTERFACE_MACRO = `; Auto-generated by Flexible Layouts - do not edit by hand
M552 S0
G4 P500
M552 T1 S1
`;

/** Uploads (or re-uploads - always just overwrites) the macro. Deployed fresh immediately before every
 *  use, rather than once during initial setup, so it can never be missing or stale on the SD card. */
export async function deployTlsEnableInterfaceMacro(io: Pick<MachineIO, "upload">): Promise<boolean> {
	try {
		await io.upload(TLS_ENABLE_INTERFACE_PATH, new Blob([TLS_ENABLE_INTERFACE_MACRO], { type: "text/plain" }));
		return true;
	} catch {
		return false;
	}
}
